# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24426c0776a52631d4de3fc4ed2b5905a458eae142de0bda0db3e1f0eb4896307f1634954e03b61578fd5ad16b60d97843cce33cc496c07ef4fa299d212247c4

test:
  secret_key_base: 6c5b02f8e78dc5e947fa547f0cc8df359f01a44c5d7f8125e88b6c7a7b0419ea31bae3e15b3faeea094529cfe7655a3206e2faa0af999e3fd39923fa9c6ab92d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
